default:
    tags:
        - LN_01
stages:
    - testing
    - build
    - deploy
testing-code:
    stage: testing
    script: 
        - echo "Pokretanje unit testova"
build-job:
    stage: build
    image: 
        name: docker:latest
    services:
        - name: docker:dind
          alias: thedockerhost
    variables:
        DOCKER_TLS_CERTDIR: ""
        DOCKER_HOST: tcp://thedockerhost:2375/
        DOCKER_DRIVER: overlay2
    script:
        - docker compose build
        - docker tag plenkyy/microfrontend-service1 plenkyy/microfrontend-service1:$CI_COMMIT_SHORT_SHA
        - docker tag plenkyy/microfrontend-service2 plenkyy/microfrontend-service2:$CI_COMMIT_SHORT_SHA
        - docker push plenkyy/microfrontend-service1:$CI_COMMIT_SHORT_SHA
        - docker push plenkyy/microfrontend-service2:$CI_COMMIT_SHORT_SHA
    before_script:
        - docker login -u $DHUB_USER -p $DHUB_PASS

deploy-job:
    stage: deploy
    image: 
        name: docker:latest
    services:
        - name: docker:dind
          alias: thedockerhostdeploy
    variables:
        DOCKER_TLS_CERTDIR: "" 
        DOCKER_HOST: tcp://thedockerhostdeploy:2375/
        DOCKER_DRIVER: overlay2
    script:
        - echo "Deploying"

