trigger: 
- master

pool:
    name: Default
    demands: 
    - agent.name -equals AzureDevOpsAgent

jobs:
  - job: BuildAndTest
    steps:
    - checkout: self   # This ensures your repository is checked out on the agent.
    
    - task: NodeTool@0
      inputs:
        versionSpec: '>=6.10.0'
      displayName: 'Instalacija Node.js packeta na Ubuntu mašinu'

    - script: pwd && npm install
      displayName: 'Instaliranje dependencija'
      workingDirectory: '$(Pipeline.Workspace)/s/CICD-POC'  # Replace with your actual project path.

    - script: npm test
      displayName: 'Pokretanje testova'
      workingDirectory: '$(Pipeline.Workspace)/s/CICD-POC'

    - script: npm run build
      displayName: 'Building project'
      workingDirectory: '$(Pipeline.Workspace)/s/./MainSite'  # If MainSite is a subdirectory.
