pr:
  branches:
    include:
    - main

pool:
    name: Default
    demands: 
    - agent.name -equals AzureDevOpsAgent

jobs:
  - job: BuildAndTest
    steps:
    - checkout: self   # This ensures your repository is checked out on the agent.
    
    - task: NodeTool@0
      inputs:
        versionSpec: '>=6.10.0'
      displayName: 'Instalacija Node.js packeta na Ubuntu mašinu'

    - script: npm install
      displayName: 'Instaliranje dependencija'
      workingDirectory: '$(Pipeline.Workspace)/s/MainSite'

    - script: echo 'Pokretanje unit testova na MainSite-u'
      displayName: 'Pokretanje testova'
      workingDirectory: '$(Pipeline.Workspace)/s/MainSite'

    - script: npm run build
      displayName: 'Building project'
      workingDirectory: '$(Pipeline.Workspace)/s/MainSit'

    - script: npm install
      displayName: 'Installing dependencies'
      workingDirectory: '$(Pipeline.Workspace)/s/reporting_host_mf'
    - script: npm build
      displayName: 'Building reporting host mf'
      workingDirectory: '$(Pipeline.Workspace)/s/reporting_host_mf'

