pr:
  branches:
    include:
    - main

pool:
  name: Default
  demands: 
  - agent.name -equals AzureDevOpsAgent

jobs:
  - job: BuildAndDeploy
    steps:
    - checkout: self  
    
    - task: NodeTool@0
      inputs:
        versionSpec: '>=6.10.0'
      displayName: 'Install Node.js'
    
    - script: npm install
      displayName: 'Install dependencies for MainSite'
      workingDirectory: '$(Pipeline.Workspace)/s/MainSite'
      
    - script: echo 'Running unit tests on MainSite'
      displayName: 'Run tests'
      workingDirectory: '$(Pipeline.Workspace)/s/MainSite'

    - script: npm run build
      displayName: 'Build MainSite project'
      workingDirectory: '$(Pipeline.Workspace)/s/MainSite'

    - script: npm install
      displayName: 'Install dependencies for reporting_host_mf'
      workingDirectory: '$(Pipeline.Workspace)/s/reporting_host_mf'
    
    - script: npm run build
      displayName: 'Build reporting_host_mf'
      workingDirectory: '$(Pipeline.Workspace)/s/reporting_host_mf'
