name: Testiranje GitHub akcija CI/CD
on:
  push:
    branches: main
jobs:
  checking-code:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Runing unit tests
      run: |
        echo "Izvođenje unit testova!\n"
        echo "cd MainSite"
        echo "npm test"
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup for NodeJS React
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Building MainSite
        run: |
          cd MainSite
          npm run build
      - name: Building reporting_site_mf
        run: |
          cd reporting_host_mf
          npm run build
